updates

diff --git a/.local/bin/ftmux b/.local/bin/ftmux
--- a/.local/bin/ftmux
+++ b/.local/bin/ftmux
@@ -129,31 +129,187 @@ createWindow() {
   fi
 }
 
+helpMenu() {
+  echo -h: help
+  echo -r: resize
+  echo -m: moneyportal
+  echo -s: "create session. followed by <session-name>"
+  echo -w: website
+  echo -n: regular sessions. followed by \"-name\"
+  echo -name:
+  echo "    -c: coding_challenges"
+  echo "    -d: demos"
+  echo "    -ds: ds_and_algos"
+  echo "    -m: m_"
+  echo "    -s: scripts"
+  echo -c: regular commands. followed by \"-cmd\"
+  echo -cmd:
+  echo "    -zs": send \"zs\" to all panes
+  echo "    -cls" send \"clear\" to all panes
+  echo "    -w: window name"
+  echo "    -p: pane id"
+  echo "    -pt: pane title"
+}
+
+zTest() {
+  if [[ -z "$*" ]]; then
+    echo "-n should have the next argument contain actual session"
+    exit 1
+  else
+    arg="$*"
+    echo YAY $arg
+    exit 1
+  fi
+}
+
+checkEmpty() {
+  arg="$1"
+  if [[ -z $arg ]]; then
+    echo "missing actual command."
+    exit 1
+  fi
+}
+
+envSession() {
+  session="env"
+  createSession $session "dots" $HOME/dots
+  createWindow $session "dwm" -c $HOME/skless/dwm
+  createWindow $session "dwmblocks" -c $HOME/skless/dwmblocks
+  createWindow $session "nvim" -c $HOME/.config/nvim
+  tw=$(getTarget $session 0 -w)
+  first=$(getTarget $tw 0 -p)
+  splitPane -v -c $HOME/dots -t $first
+  tw=$(getTarget $session -1 -w)
+  splitPane -v -c $HOME/env -t $(getTarget $tw 0 -p)
+}
+
+finalSession() {
+  session="project-work"
+  createSession $session "main" $DEV/Code/py/ml
+  createWindow $session "run" -c $DEV/Code/project-work
+  tw=$(getTarget $session 0 -w)
+  tw2=$(getTarget $session 1 -w)
+  second=$(getTarget $tw2 0 -p)
+  $X send-keys -t $(getTarget $tw 0 -p) "conda activate project-work" "C-m"
+  $X send-keys -t $second "conda activate project-work" "C-m"
+  $X send-keys -t $second "jupyter lab" "C-m"
+}
+
+moneyportalSession() {
+  session="money-portal"
+  createSession $session "code" $MONEYPORTAL
+  createWindow $session "run" -c $MONEYPORTAL/web
+  createWindow $session "psql-redis" -c $MONEYPORTAL/server
+  createWindow $session "docker-azure" -c $MONEYPORTAL/server
+
+  # First Window
+  tw=$(getTarget $session 0 -w)
+  $X send-keys -t $(getTarget $tw 0 -p) "nvim" "C-m"
+
+  # Second Window
+  tw=$(getTarget $session 1 -w)
+  first=$(getTarget $tw 0 -p)
+  $X send-keys -t $first "yarn dev" "C-m"
+  splitPane -v -c $MONEYPORTAL/server -t $first
+  second=$(getTarget $tw 1 -p)
+  $X send-keys -t $second "yarn watch" "C-m"
+  splitPane -h -c $MONEYPORTAL/server -t $second
+  third=$(getTarget $tw 2 -p)
+  $X send-keys -t $third "yarn dev" "C-m"
+
+  # Third Window
+  tw=$(getTarget $session 2 -w)
+  first=$(getTarget $tw 0 -p)
+  $X send-keys -t $first "psql -U postgres" "C-m"
+  splitPane -v -c $MONEYPORTAL/server -t $first
+  second=$(getTarget $tw -1 -p)
+  $X send-keys -t $second "redis-cli ping" "C-m"
+
+  # Fourth Window
+  tw=$(getTarget $session 3 -w)
+  first=$(getTarget $tw 0 -p)
+  $X send-keys -t $first "docker info" "C-m"
+  splitPane -v -c $MONEYPORTAL/server -t $first
+  $X send-keys -t $(getTarget $tw -1 -p) "az --h" "C-m"
+}
+
+websiteSession() {
+  session="website"
+  createSession $session "code" $WEBSITE
+  createWindow $session "run" -c $WEBSITE
+  createWindow $session "v1" -c $V1
+
+  # First Window
+  tw=$(getTarget $session 0 -w)
+  first=$(getTarget $tw 0 -p)
+  $X send-keys -t $first "nv src/pages/index.tsx" "C-m"
+
+  # Second Window
+  tw=$(getTarget $session 1 -w)
+  first=$(getTarget $tw 0 -p)
+  $X send-keys -t $first "git status" "C-m"
+  splitPane -v -c $WEBSITE -t $first
+  second=$(getTarget $tw 1 -p)
+  # $X send-keys -t $second "npm run develop" "C-m"
+  splitPane -h -c $WEBSITE -t $second
+  third=$(getTarget $tw 2 -p)
+  $X send-keys -t $third "cdocs" "C-m"
+
+  # Third Window
+  tw=$(getTarget $session 2 -w)
+  first=$(getTarget $tw 0 -p)
+  $X send-keys -t $first "nv src/pages/index.js" "C-m"
+}
+
+ccSession() {
+  session="coding_challenges"
+  createSession $session main $CC
+  tw=$(getTarget $session 0 -w)
+  first=$(getTarget $tw 0 -p)
+  splitPane -v -c $CC -t $first
+}
+
+demosSession() {
+  session="demos"
+  createSession $session main $DEMOS
+  tw=$(getTarget $session 0 -w)
+  first=$(getTarget $tw 0 -p)
+  splitPane -v -c $DEMOS -t $first
+}
+
+dsSession() {
+  session="ds_and_algos"
+  createSession $session main $DS
+  tw=$(getTarget $session 0 -w)
+  first=$(getTarget $tw 0 -p)
+  splitPane -v -c $DS -t $first
+}
+
+mSession() {
+  session="m_"
+  createSession $session main $C_NVIM
+  createWindow $session "init" -c $NVIM
+  tw=$(getTarget $session 0 -w)
+  first=$(getTarget $tw 0 -p)
+  splitPane -v -c $DOCS -t $first
+}
+
+scriptsSession() {
+  session="scripts"
+  createSession $session main $SCRIPTS
+  createWindow $session "bin" -c $HOME/.local/bin
+  tw=$(getTarget $session 0 -w)
+  first=$(getTarget $tw 0 -p)
+  splitPane -v -c $SCRIPTS -t $first
+}
+
 while [[ "$#" -gt 0 ]]; do
   curr=$1
   shift
 
   case "$curr" in
     "-h")
-      echo -h: help
-      echo -r: resize
-      echo -m: moneyportal
-      echo -s: "create session. followed by <session-name>"
-      echo -w: website
-      echo -n: regular sessions. followed by \"-name\"
-      echo -name:
-      echo "    -c: coding_challenges"
-      echo "    -d: demos"
-      echo "    -ds: ds_and_algos"
-      echo "    -m: m_"
-      echo "    -s: scripts"
-      echo -c: regular commands. followed by \"-cmd\"
-      echo -cmd:
-      echo "    -zs": send \"zs\" to all panes
-      echo "    -cls" send \"clear\" to all panes
-      echo "    -w: window name"
-      echo "    -p: pane id"
-      echo "    -pt: pane title"
+      helpMenu
       ;;
     "-c")
       arg=$1
@@ -199,10 +355,7 @@ while [[ "$#" -gt 0 ]]; do
     ;;
   "-k")
     arg=$1
-    if [[ -z $arg ]]; then
-      echo "-c should have the next argument contain -target"
-      exit 1
-    fi
+    checkEmpty $args
     shift
     case "$arg" in
       "-p")
@@ -223,163 +376,48 @@ while [[ "$#" -gt 0 ]]; do
   "-b")
     breakPane
     ;;
-  "-ap")
-    OUTPUT=$(pwd)
-    echo pwd: "${OUTPUT}"
-    ;;
   "-s")
-    if [[ -z "$*" ]]; then
-      echo "-n should have the next argument contain actual session"
-      exit 1
-    else
-      session="$*"
-      echo session: $session
-      createSession ${session} "main"
-      exit 1
-    fi
+    arg=$1
+    checkEmpty $arg
+    shift
+    session="$arg"
+    createSession ${session} "main"
+    echo session: $session
     ;;
   "-z")
-    if [[ -z "$*" ]]; then
-      echo "-n should have the next argument contain actual session"
-      exit 1
-    else
-      arg="$*"
-      echo YAY $arg
-      exit 1
-    fi
+    zTest
     ;;
   "-env")
-    session="env"
-    createSession $session "dots" $HOME/dots
-    createWindow $session "dwm" -c $HOME/skless/dwm
-    createWindow $session "dwmblocks" -c $HOME/skless/dwmblocks
-    createWindow $session "nvim" -c $HOME/.config/nvim
-    tw=$(getTarget $session 0 -w)
-    first=$(getTarget $tw 0 -p)
-    splitPane -v -c $HOME/dots -t $first
-    tw=$(getTarget $session -1 -w)
-    splitPane -v -c $HOME/env -t $(getTarget $tw 0 -p)
+    envSession
     ;;
   "-final")
-    session="project-work"
-    createSession $session "main" $DEV/Code/py/ml
-    createWindow $session "run" -c $DEV/Code/project-work
-    tw=$(getTarget $session 0 -w)
-    tw2=$(getTarget $session 1 -w)
-    second=$(getTarget $tw2 0 -p)
-    $X send-keys -t $(getTarget $tw 0 -p) "conda activate project-work" "C-m"
-    $X send-keys -t $second "conda activate project-work" "C-m"
-    $X send-keys -t $second "jupyter lab" "C-m"
+    finalSession
     ;;
   "-m")
-    session="money-portal"
-    createSession $session "code" $MONEYPORTAL
-    createWindow $session "run" -c $MONEYPORTAL/web
-    createWindow $session "psql-redis" -c $MONEYPORTAL/server
-    createWindow $session "docker-azure" -c $MONEYPORTAL/server
-
-    # First Window
-    tw=$(getTarget $session 0 -w)
-    $X send-keys -t $(getTarget $tw 0 -p) "nvim" "C-m"
-
-    # Second Window
-    tw=$(getTarget $session 1 -w)
-    first=$(getTarget $tw 0 -p)
-    $X send-keys -t $first "yarn dev" "C-m"
-    splitPane -v -c $MONEYPORTAL/server -t $first
-    second=$(getTarget $tw 1 -p)
-    $X send-keys -t $second "yarn watch" "C-m"
-    splitPane -h -c $MONEYPORTAL/server -t $second
-    third=$(getTarget $tw 2 -p)
-    $X send-keys -t $third "yarn dev" "C-m"
-
-    # Third Window
-    tw=$(getTarget $session 2 -w)
-    first=$(getTarget $tw 0 -p)
-    $X send-keys -t $first "psql -U postgres" "C-m"
-    splitPane -v -c $MONEYPORTAL/server -t $first
-    second=$(getTarget $tw -1 -p)
-    $X send-keys -t $second "redis-cli ping" "C-m"
-
-    # Fourth Window
-    tw=$(getTarget $session 3 -w)
-    first=$(getTarget $tw 0 -p)
-    $X send-keys -t $first "docker info" "C-m"
-    splitPane -v -c $MONEYPORTAL/server -t $first
-    $X send-keys -t $(getTarget $tw -1 -p) "az --h" "C-m"
+    moneyportalSession
     ;;
   "-w")
-    session="website"
-    createSession $session "code" $WEBSITE
-    createWindow $session "run" -c $WEBSITE
-    createWindow $session "v1" -c $V1
-
-    # First Window
-    tw=$(getTarget $session 0 -w)
-    first=$(getTarget $tw 0 -p)
-    $X send-keys -t $first "nv src/pages/index.tsx" "C-m"
-
-    # Second Window
-    tw=$(getTarget $session 1 -w)
-    first=$(getTarget $tw 0 -p)
-    $X send-keys -t $first "git status" "C-m"
-    splitPane -v -c $WEBSITE -t $first
-    second=$(getTarget $tw 1 -p)
-    # $X send-keys -t $second "npm run develop" "C-m"
-    splitPane -h -c $WEBSITE -t $second
-    third=$(getTarget $tw 2 -p)
-    $X send-keys -t $third "cdocs" "C-m"
-
-    # Third Window
-    tw=$(getTarget $session 2 -w)
-    first=$(getTarget $tw 0 -p)
-    $X send-keys -t $first "nv src/pages/index.js" "C-m"
+    websiteSession
     ;;
-
   "-n")
     arg=$1
-    if [[ -z $arg ]]; then
-      echo "-n should have the next argument contain actual session"
-      exit 1
-    fi
+    checkEmpty $arg
     shift
     case "$arg" in
     "-c")
-      session="coding_challenges"
-      createSession $session main $CC
-      tw=$(getTarget $session 0 -w)
-      first=$(getTarget $tw 0 -p)
-      splitPane -v -c $CC -t $first
+      ccSession
       ;;
     "-d")
-      session="demos"
-      createSession $session main $DEMOS
-      tw=$(getTarget $session 0 -w)
-      first=$(getTarget $tw 0 -p)
-      splitPane -v -c $DEMOS -t $first
+      demosSession
       ;;
     "-ds")
-      session="ds_and_algos"
-      createSession $session main $DS
-      tw=$(getTarget $session 0 -w)
-      first=$(getTarget $tw 0 -p)
-      splitPane -v -c $DS -t $first
+      dsSession
       ;;
     "-m")
-      session="m_"
-      createSession $session main $C_NVIM
-      createWindow $session "init" -c $NVIM
-      tw=$(getTarget $session 0 -w)
-      first=$(getTarget $tw 0 -p)
-      splitPane -v -c $DOCS -t $first
+      mSession
       ;;
     "-s")
-      session="scripts"
-      createSession $session main $SCRIPTS
-      createWindow $session "bin" -c $HOME/.local/bin
-      tw=$(getTarget $session 0 -w)
-      first=$(getTarget $tw 0 -p)
-      splitPane -v -c $SCRIPTS -t $first
+      scriptsSession
       ;;
     *) echo "Unavailable command... $arg"
     esac
